# Generated by Django 2.2.2 on 2019-12-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorepost', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Disgusting'), (2, 'Not Too Helpful'), (3, 'Not So Informative'), (4, 'Informative'), (5, 'Helpful And Informative')], null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorepost.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
