# Generated by Django 2.2.2 on 2019-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorepost', '0004_auto_20191224_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthit',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
