# Generated by Django 2.2.2 on 2019-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
