# Generated by Django 2.2.2 on 2019-08-19 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exploreuser', '0002_auto_20190713_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
