# Generated by Django 2.2.2 on 2019-09-29 08:51

from django.db import migrations, models
import exploreuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreuser', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=exploreuser.models.profile_img_path),
        ),
    ]
